### ISSUE TITLE
Settings Editor

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#128]
The settings editor is not functional in this stage. The configurations done from the editor won't take effect on the actual config. Implementing the settings editor is important. Atleast biscuit should open the configuration files when asked for settings to edit the config within biscuit itself for now.

**Comment by vyshnav-vinod** [comment]
Ok so i noticed this issue while using the editor and found that the settings page does not do anything and configs are not saved. I was thinking since it is using `CheckButton()` maybe we can utilize the [command](https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/ttk-Checkbutton.html) argument of `CheckButton()` and maybe call a function which will change the configs and whenever the editor is closed, only then we actually write into `settings.toml` instead of writing it to `settings.toml` everytime we change a setting.

**Comment by billyeatcookies** [comment]
The config loader part of biscuit was removed temporarily as I thought of rewriting it properly. So currently biscuit doesn't load or handle any config files. Though I'd like the community's suggestions on writing a new system in place.

- **Use of sqlite3 databases instead of json/toml files**
  this would make the configurations only changeable within the editor (from settings editor)
-
